[package]
name = "Backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
diesel = { version = "2.0.0", features = ["postgres"] }
dotenvy = "0.15"
chrono = { version = "0.4", features = ["serde"] }