[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
diesel = { version = "2.0.0", features = ["postgres"] }
dotenvy = "0.15"
r2d2 = "0.8.9"

# [[bin]]
# name = "config"
# path = "src/config/config.rs"